/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArrowLeftIcon: typeof import('./src/components/icons/ArrowLeftIcon.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    HomeHero: typeof import('./src/components/HomeHero.vue')['default']
    LangIcon: typeof import('./src/components/icons/LangIcon.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeDarkIcon: typeof import('./src/components/icons/ThemeDarkIcon.vue')['default']
    ThemeLightIcon: typeof import('./src/components/icons/ThemeLightIcon.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
    ToggleDarkMode: typeof import('./src/components/ToggleDarkMode.vue')['default']
    ToggleLanguage: typeof import('./src/components/ToggleLanguage.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
